version: "3"

services:
  dev:
    build: #address of docker-compose
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: #linking volumes
      - /var/app/node_modules #it will not serve this modules from the development/ will serve them directly from inside the container
      - .:/var/app

  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    
    volumes:
      - /var/app/node_modules 
      - .:/var/app
    command: ["npm", "run", "test"]  





    