FROM node:alpine

WORKDIR /var/app

# package.json into the current working dir
COPY package.json ./

RUN npm install

# copy rest of all the files go into my workdir
COPY . .

CMD [ "npm", "run", "start" ]